### PR TITLE
On unhandled runtime exception windows clients can opt to continue se…

### LINKED ISSUE #961: Top level exception filter
Hello,
I have an application in two variants. The _NET_ variant consumes a C# assembly via an C++/CLI bridge, while the _AOT_ variant links the assembly after building it into a static native AOT lib.

The C# assembly targets `netcore5.0` and runtime `win-x64`.
The application uses a SEH top level exception filter installed via `SetUnhandledExceptionFilter `to report crashes to developers.

Unhandled exceptions in the _NET_ application actually get reported via the installed top level filter.
Unhandled exceptions in the _AOT_ application never make it to the top level filter and the application is killed silently.
Even with some hacking that ensures that our top level filter cannot be replaced after being installed unhandled exceptions in the _AOT_ application never make it there.

**1)** Is the top level SEH filter mechanism used at all when dealing with unhandled exceptions?
**2)** How does process termination due to unhandled exception work?

I appreciate any answers, help, pointers!

Best,
dirk

### PR DESCRIPTION
**Pull request by distee-ubi**
…arch for handlers
Amends already closed #961

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtimelab?pullRequest=1149) <br/>All CLA requirements met.

File: src/coreclr/nativeaot/Runtime/EHHelpers.cpp [hunk 1]
```diff
@@ -449,6 +449,18 @@ int32_t __stdcall RhpHardwareExceptionHandler(uintptr_t faultCode, uintptr_t fau
 
 #else // TARGET_UNIX
 
+static bool g_ContinueSearchOnUnhandledRuntimeException = false;
+
+// Set the runtime to continue search when encountering an unhandled runtime exception. Once done it is forever.
+// Continuing the search allows any vectored exception handlers or SEH installed by the client to take effect.
+// Any client that does so is expected to handle stack overflows.
+EXTERN_C bool RhpContinueSearchOnUnhandledRuntimeException()
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/EHHelpers.cpp]:
```suggestion
EXTERN_C void RhpContinueOnFatalErrors()
```
The previous value is not really useful since the setting is applied forever. Also, I think fatal error better describes what this does.

File: src/coreclr/nativeaot/Runtime/EHHelpers.cpp [hunk 2]
```diff
@@ -477,8 +489,13 @@ int32_t __stdcall RhpVectoredExceptionHandler(PEXCEPTION_POINTERS pExPtrs)
         }
         else if (faultCode == STATUS_STACK_OVERFLOW)
         {
-            // Do not use ASSERT_UNCONDITIONALLY here. It will crash because of it consumes too much stack.
+            if(g_ContinueSearchOnUnhandledRuntimeException)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/EHHelpers.cpp]:
```suggestion
            if (g_ContinueSearchOnUnhandledRuntimeException)
```
Nit

File: src/coreclr/nativeaot/Runtime/EHHelpers.cpp [hunk 3]
```diff
@@ -515,6 +532,10 @@ int32_t __stdcall RhpVectoredExceptionHandler(PEXCEPTION_POINTERS pExPtrs)
         return EXCEPTION_CONTINUE_EXECUTION;
     }
 
+    // The client may have told us to continue to search for custom handlers,
+    // but in general we consider any form of hardware exception within the runtime itself a fatal error.
+    // Note this includes the managed code within the runtime.
+    if(!g_ContinueSearchOnUnhandledRuntimeException)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/EHHelpers.cpp]:
```suggestion
    if (!g_ContinueSearchOnUnhandledRuntimeException)
```
Nit

File: src/coreclr/nativeaot/Runtime/EHHelpers.cpp (hunk 1 above)
Comment (distee-ubi) [reply src/coreclr/nativeaot/Runtime/EHHelpers.cpp]: The return allows you to realize you did a second call to no effect, but I agree that this is not really useful.
I like 'FatalError' better than 'ContinueSearchOnUnh....'. It is also much shorter! I'll change the naming of the setter and the variable it acts on.

File: src/coreclr/nativeaot/Runtime/EHHelpers.cpp (hunk 2 above)
Comment (distee-ubi) [reply src/coreclr/nativeaot/Runtime/EHHelpers.cpp]: ah, habits ... will fix this.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by distee-ubi** [comment]
Thanks for your help!
