### PR TITLE
[NativeAOT-LLVM] Add tracked SSA locals to the first basic block LiveIn set.

### LINKED ISSUE #2682: [NativeAOT-LLVM] Ilc assert with locals in release config
This IL seems to cause an assert
```
// [PresentationFramework]System.Windows.FrameworkTemplate.WireRootObjectToParent(object,DependencyObject,DependencyObject,FrameworkElement,INameScope)
.method class [WindowsBase]System.Windows.DependencyObject WireRootObjectToParent(object, class [WindowsBase]System.Windows.DependencyObject, class [WindowsBase]System.Windows.DependencyObject, class System.Windows.FrameworkElement, class [System.Xaml]System.Windows.Markup.INameScope) cil managed
{
  // Code size: 124
  .maxstack 5
  .locals init (class [PresentationCore]System.Windows.UIElement V_0,
      class System.Windows.FrameworkElement V_1,
      class System.Windows.FrameworkContentElement V_2)

  IL_0000:  ldarg.0
  IL_0001:  isinst      [WindowsBase]System.Windows.DependencyObject
  IL_0006:  starg.s     1
  IL_0008:  ldarg.1
  IL_0009:  brfalse.s   IL_007A
  IL_000B:  ldarg.3
  IL_000C:  brfalse.s   IL_0045
  IL_000E:  ldarg.1
  IL_000F:  isinst      [PresentationCore]System.Windows.UIElement
  IL_0014:  stloc.0
  IL_0015:  ldloc.0
  IL_0016:  brtrue.s    IL_003C
  IL_0018:  ldstr       "TemplateMustBeFE"
  IL_001D:  ldc.i4.1
  IL_001E:  newarr      object
  IL_0023:  dup
  IL_0024:  ldc.i4.0
  IL_0025:  ldarg.1
  IL_0026:  callvirt    instance class [System.Private.CoreLib]System.Type [System.Private.CoreLib]System.Object::GetType()
  IL_002B:  callvirt    instance string [System.Private.CoreLib]System.Type::get_FullName()
  IL_0030:  stelem.ref
  IL_0031:  call        string System.Windows.SR::Get(string, object[])
  IL_0036:  newobj      instance void [System.Private.CoreLib]System.InvalidOperationException::.ctor(string)
  IL_003B:  throw
  IL_003C:  ldarg.3
  IL_003D:  ldloc.0
  IL_003E:  callvirt    instance void System.Windows.FrameworkElement::set_TemplateChild(class [PresentationCore]System.Windows.UIElement)
  IL_0043:  br.s        IL_006A
  IL_0045:  ldarg.2
  IL_0046:  brfalse.s   IL_006A
  IL_0048:  ldarg.1
  IL_0049:  ldloca.s    1
  IL_004B:  ldloca.s    2
  IL_004D:  ldc.i4.1
  IL_004E:  call        void MS.Internal.Helper::DowncastToFEorFCE(class [WindowsBase]System.Windows.DependencyObject, class System.Windows.FrameworkElement&, class System.Windows.FrameworkContentElement&, bool)
  IL_0053:  ldarg.2
  IL_0054:  castclass   System.Windows.FrameworkContentElement
  IL_0059:  ldarg.1
  IL_005A:  callvirt    instance class [System.Private.CoreLib]System.Type [System.Private.CoreLib]System.Object::GetType()
  IL_005F:  ldloc.1
  IL_0060:  ldnull
  IL_0061:  cgt.un
  IL_0063:  ldloc.1
  IL_0064:  ldloc.2
  IL_0065:  call        void System.Windows.FrameworkElementFactory::AddNodeToLogicalTree(class [WindowsBase]System.Windows.DependencyObject, class [System.Private.CoreLib]System.Type, bool, class System.Windows.FrameworkElement, class System.Windows.FrameworkContentElement)
  IL_006A:  ldarg.1
  IL_006B:  call        class [System.Xaml]System.Windows.Markup.INameScope [WindowsBase]System.Windows.NameScope::GetNameScope(class [WindowsBase]System.Windows.DependencyObject)
  IL_0070:  brtrue.s    IL_007A
  IL_0072:  ldarg.1
  IL_0073:  ldarg.s     4
  IL_0075:  call        void [WindowsBase]System.Windows.NameScope::SetNameScope(class [WindowsBase]System.Windows.DependencyObject, class [System.Xaml]System.Windows.Markup.INameScope)
  IL_007A:  ldarg.1
  IL_007B:  ret
}
```
at https://github.com/dotnet/runtimelab/blob/409591fa1363a89d1bbce4daf7ab1a414de8b3df/src/coreclr/jit/llvmcodegen.cpp#L1191

Haven't done any more investigation

image

### PR DESCRIPTION
**Pull request by yowl**
This PR adds tracked SSA variables to the Live In set for the first basic block, fixing an assert in release config.  

Fixes #2682

### CODE REVIEW

**Comment by yowl** [comment]
cc @dotnet/nativeaot-llvm 

Thanks @SingleAccretion  for the fix.

File: src/coreclr/jit/llvmlssa.cpp [hunk 1]
```diff
@@ -986,6 +986,10 @@ class ShadowStackAllocator
                     if (m_compiler->lvaInSsa(lclNum))
                     {
                         initValue->SetSsaNum(SsaConfig::FIRST_SSA_NUM);
+                        if (varDsc->lvTracked)
+                        {
+                            VarSetOps::AddElemD(m_compiler, m_compiler->fgFirstBB->bbLiveIn, varDsc->lvVarIndex);
+                        }
                     }
```
Comment (SingleAccretion) [inline src/coreclr/jit/llvmlssa.cpp]:
```suggestion
                    if (m_compiler->lvaInSsa(lclNum))
                    {
                        // Fortunately for the implicit GC def logic, SSA always adds an implicit def for parameters.
                        assert(varDsc->GetPerSsaData(SsaConfig::FIRST_SSA_NUM)->GetDefNode() == nullptr);
                        initValue->SetSsaNum(SsaConfig::FIRST_SSA_NUM);
                    }
                    if (varDsc->lvTracked)
                    {
                        VarSetOps::AddElemD(m_compiler, m_compiler->fgFirstBB->bbLiveIn, varDsc->lvVarIndex);
                    }
```
Not all locals that are tracked have to be in SSA (the opposite is true, however).

The assert is important because, if SSA was more precise, and did not add implicit defs for locals like below:
```
Func(object a) {
   SafePoint();
   a = new object(); // Immediately overwritten. Consider 
}
```
The liveness data would become out of sync with SSA. Liveness would day "this value is used before `a = new object()`", SSA would say "there is no definition of `a` before `a = new object()`". In fact, the existing `SetSsaNum` logic also relies on this.

**Review by SingleAccretion — COMMENTED** [review]
Could you also add a test for this case?

**Comment by yowl** [comment]
> Could you also add a test for this case?

Any idea what that would look like?  I tried a few things, but not sure exactly what triggered the error.

**Comment by SingleAccretion** [comment]
> Any idea what that would look like? I tried a few things, but not sure exactly what triggered the error.

It should cause the initial and unused definition of a tracked parameter to become live due to a safe point between it and the first (actual) definition. So, something like:
```cs
object func(object a) {
   SafePoint();
   a = new object();
   SafePoint(); // Force 'a' to the shadow stack
   return a;
}
```

**Comment by yowl** [comment]
Thanks, that does it.

**Review by SingleAccretion — APPROVED** [review]
LGTM. Thank you!
