### PR TITLE
NativeAOT-LLVM: Change test for canStoreArgOnLlvmStack to typGetObjLayout/HasGCPtr

### LINKED ISSUE #2049: [NativeAOT-LLVM, WASM] double/float 64, RuntimeError: table index is out of bounds
Hi,
It appears that if you use double type then program will crash with following error:
```
RuntimeError: table index is out of bounds
    at RhpGcAlloc (wasm://wasm/04797806:wasm-function[19138]:0xb6f08b)
    at RhpNewArray (wasm://wasm/04797806:wasm-function[19236]:0xb7001e)
    at S_P_CoreLib_System_Diagnostics_StackTrace__InitializeForCurrentThread (wasm://wasm/04797806:wasm-function[4618]:0x3fe169)
    at S_P_CoreLib_System_Diagnostics_StackTrace___ctor_1 (wasm://wasm/04797806:wasm-function[12269]:0x973f35)
    at S_P_CoreLib_System_Exception__DispatchExLLVM (wasm://wasm/04797806:wasm-function[13820]:0x9cfcef)
    at S_P_CoreLib_System_SR__InternalGetResourceString$CatchFA (wasm://wasm/04797806:wasm-function[5272]:0x4def93)
    at LlvmCatchFunclet (wasm://wasm/04797806:wasm-function[269]:0x359c1)
    at RhpCallCatchFunclet (wasm://wasm/04797806:wasm-function[19923]:0xbadf35)
    at S_P_CoreLib_System_SR__InternalGetResourceString (wasm://wasm/04797806:wasm-function[4958]:0x476dc9)
    at invoke_vii (C:\Users\Kanawanagasaki\Desktop\qwe\bin\Debug\net7.0\browser-wasm\native\qwe.js:5187:29)
```

### Steps to reproduce:
1. `mkdir NativeAOTLLVMTest`
2. `cd NativeAOTLLVMTest`
3. `dotnet new console`
4. `dotnet new nugetconfig`
5. in nuget.config add
```
<add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
```
6. in NativeAOTLLVMTest.csproj add
```
<ItemGroup>
  <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM; runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*" />
</ItemGroup>
```
7. change Program.cs to
```cs
Console.WriteLine(1d);
```
8. `dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false --self-contained`
9. `cd .\bin\Debug\net7.0\browser-wasm\native`
10. `node .\NativeAOTLLVMTest.js`

### PR DESCRIPTION
**Pull request by yowl**
This PR changes the condition for `canStoreArgOnLlvmStack ` to use `ClassLayout.HasGCPtr` 

Fixes #2049

by virtue of placing `DiyFp` on the LLVM stack to match the calls from the IL module.

Also took the liberty of allowing return types of `TYP_STRUCT` as all the code was in place.   

And a few lines for `CORINFO_HELP_THROW_PLATFORM_NOT_SUPPORTED` as that was asserting.  Not supported though as its missing an `unreachable` after the call.

cc @SingleAccretion

### CODE REVIEW

File: src/coreclr/jit/llvm.cpp [hunk 1]
```diff
@@ -537,15 +537,14 @@ bool canStoreLocalOnLlvmStack(LclVarDsc* varDsc)
     return !varDsc->HasGCPtr();
 }
 
-static bool canStoreArgOnLlvmStack(Compiler::Info &info, CorInfoType corInfoType, CORINFO_CLASS_HANDLE classHnd)
+static bool canStoreArgOnLlvmStack(Compiler* compiler, CorInfoType corInfoType, CORINFO_CLASS_HANDLE classHnd)
 {
     // structs with no GC pointers can go on LLVM stack.
     if (corInfoType == CorInfoType::CORINFO_TYPE_VALUECLASS)
     {
         // Use getClassAtribs over typGetObjLayout because EETypePtr has CORINFO_FLG_GENERIC_TYPE_VARIABLE? which fails with typGetObjLayout
```
Comment (SingleAccretion) [inline src/coreclr/jit/llvm.cpp]:
```suggestion
```
(Presumably)

**Review by SingleAccretion — APPROVED** [review]

File: src/coreclr/jit/llvm.cpp (hunk 1 above)
Comment (yowl) [reply src/coreclr/jit/llvm.cpp]: Yes, it doesn't seem to be a problem anymore.  Thanks
