### PR TITLE
Define the inner P/Invokes as local functions instead of externally.

### LINKED ISSUE #1064: Generated source fails to compile for overloaded functions that map to the same blittable signature
The source generator does not handle overloads of a function where that the signature of the generated blittable P/Invoke would be the same, resulting in `CS0111` (Type 'class' already defines a member called 'member' with the same parameter types).

Common use cases from runtime libraries

Safe handles
```C#
[GeneratedDllImport(NativeExportsNE_Binary, EntryPoint = "use_handle")]
public static partial void UseHandle(IntPtr handle);

[GeneratedDllImport(NativeExportsNE_Binary, EntryPoint = "use_handle")]
public static partial void UseHandle(SafeFileHandle handle);

[GeneratedDllImport(NativeExportsNE_Binary, EntryPoint = "use_handle")]
public static partial void UseHandle(SafePipeHandle handle);
```
Results in defining the same p/invoke three times:
```C
[System.Runtime.InteropServices.DllImportAttribute("Microsoft.Interop.Tests.NativeExportsNE", EntryPoint = "use_handle")]
extern private static unsafe void UseHandle__PInvoke__(global::System.IntPtr handle);
```

Arrays
```C#
[GeneratedDllImport(NativeExportsNE_Binary, EntryPoint = "sum_int_array")]
public static partial int Sum(int[] values, int numValues);

[GeneratedDllImport(NativeExportsNE_Binary, EntryPoint = "sum_int_array")]
public static partial int Sum(ref int values, int numValues);
```
Results in defining the same p/invoke twice:
```C#
[System.Runtime.InteropServices.DllImportAttribute("Microsoft.Interop.Tests.NativeExportsNE", EntryPoint = "sum_int_array")]
extern private static unsafe int Sum__PInvoke__(int* values, int numValues);
```

cc @AaronRobinsonMSFT @jkoritzinsky

### PR DESCRIPTION
**Pull request by jkoritzinsky**
My previous PR got auto-closed due to git shenanigans, so I'm reopening it here.

This is an alternative to https://github.com/dotnet/runtimelab/pull/1081.

This implementation makes the inner P/Invokes not conflict by making them completely internal instead of attempting reuse between the different methods. This way we won't need to track the DllImport info for the target in the same manner that #1081 does.

Fixes #1064

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
I like this very much. <3

File: DllImportGenerator/DllImportGenerator/StubCodeGenerator.cs [hunk 1]
```diff
@@ -340,20 +340,22 @@ public override (string managed, string native) GetIdentifiers(TypePositionInfo
             var codeBlock = Block(UnsafeStatement(Block(allStatements)));
 
             // Define P/Invoke declaration
-            var dllImport = MethodDeclaration(retMarshaller.Generator.AsNativeType(retMarshaller.TypeInfo), dllImportName)
+            var dllImport = LocalFunctionStatement(retMarshaller.Generator.AsNativeType(retMarshaller.TypeInfo), dllImportName)
```
Comment (AaronRobinsonMSFT) [inline DllImportGenerator/DllImportGenerator/StubCodeGenerator.cs:343]: My only question here would be how does this align with our desire to use this as a library? At first glance it seems this makes the stub generator even more tightly coupled to the `DllImport` scenario &ndash; which actually seems fine. Does this have any influence on the overall design and how it may expand?

Comment (jkoritzinsky) [reply DllImportGenerator/DllImportGenerator/StubCodeGenerator.cs:343]: This should still enable our intent to use as a library. This change actually makes the whole `DllImport` scenario contained within `StubCodeGenerator.cs`.

The main question we need to answer is how we want to make this library extensible.

Do we want to enable people to provide their own set of default marshalling rules but still generate the internal stub code the same as StubCodeGenerator? Then we'll want to refactor MarshallingGenerator.Create to be an interface method, provide a default class implementation with our defaults, and pass it down to StubCodeGenerator.

Do we want to enable people to use the default generators but change the body of the function while preserving some parts (like the target dllimport function declaration)? Then we can extract this declaration along with other self-contained phases to separate protected functions that users can call when they're building their code-gen. For example, if someone wanted to build a generator that's basically identical to ours but used function pointers, they could override the code-gen to not produce this local function declaration and change the invoke stage to instead call their function pointer.

Do we want to enable people to build source generators for completely different scenarios like struct or COM-style marshalling? Then we just need a solidified design for our marshallers and the base StubCodeContext type and everyone else builds on top of those.

Comment (AaronRobinsonMSFT) [reply DllImportGenerator/DllImportGenerator/StubCodeGenerator.cs:343]: >Do we want to enable people to build source generators for completely different scenarios like struct or COM-style marshalling? Then we just need a solidified design for our marshallers and the base StubCodeContext type and everyone else builds on top of those.

Yes.

**Review by AaronRobinsonMSFT — APPROVED** [review]
