### PR TITLE
[NativeAOT-LLVM] Fix EH with table-disjoint mutually protecting handlers

### LINKED ISSUE #2641: [NativeAOT-LLVM] Compilation failure with async/EH/lock
The following, distilled from https://github.com/dotnet/runtimelab/blob/53dc49532ac2d8e49c739d784515d66ef0434851/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/BrowserWebSockets/BrowserWebSocket.cs#L316
```c#
public class SafeContext
{
    private static object _lockObject = new object();

    class OperationCanceledException : Exception
    { }

    public static async Task ConnectAsyncCore(CancellationToken cancellationToken)
    {
        Task openTask;

        try
        {
            await Task.CompletedTask;
        }
        catch (OperationCanceledException ex)
        {
            throw;
        }
        catch (Exception)
        {
            lock (_lockObject)
            {
            }
            throw;
        }
    }
}

```

Causes an assert in the LLVM verification
```
    Unwind edges out of a funclet pad must have the same unwind dest
      %225 = catchpad within %224 [ptr null], !dbg !5841
      invoke void @llvm.wasm.rethrow() [ "funclet"(token %225) ]
              to label %BT00.4 unwind label %BT02.1, !dbg !5841
      invoke void @RhpRethrow(ptr %142, ptr %141) [ "funclet"(token %225) ]
              to label %BB15.6 unwind label %BT03.1, !dbg !5849
    Assertion failed: !llvm::verifyFunction(*llvmFunc, &llvm::errs()), file C:\github\runtimelab\src\coreclr\jit\llvmcodegen.cpp, l
  ine 830
    abort() has been called
```
This test is added to the branch, https://github.com/yowl/runtimelab/tree/async-eh, although that is based on the linux CI work, the last commit should be cherry pickable.

cc @SingleAccretion

### PR DESCRIPTION
**Pull request by SingleAccretion**
As it turns out, EH table entries of mutually protecting handlers do not have to be immediately adjacent (despite what some comments in the Jit claim...). The dispatch code I wrote some time back made such an assumption, and this change fixes that.

Fixes #2641.

### CODE REVIEW

File: src/coreclr/jit/llvmcodegen.cpp [hunk 1]
```diff
@@ -380,10 +381,35 @@ void Llvm::generateUnwindBlocks()
         });
     }
 
+    // The main loop will need to map an outermost mutually protecting region to the innermost. While usually
+    // mutually protecting handlers form a contiguous 'run' in the table, this is not guaranteed, and disjoint
+    // regions, or regions nested inside the respective handlers can 'break up' the run.
```
Comment (SingleAccretion) [inline src/coreclr/jit/llvmcodegen.cpp:386]: Here's the EH table from the test:
```scala
***************  Exception Handling table
index  eTry, eHnd
  0  ::   6        - Try at BB02..BB02 [000..00C), Handler at BB03..BB03 [00C..015)
  1  ::   4     6  - Try at BB05..BB05 [016..022), Handler at BB06..BB06 [022..02B)
  2  ::   3     4  - Try at BB08..BB08 [02C..038), Handler at BB09..BB09 [038..041)
  3  ::   8     4  - Try at BB08..BB10 [02C..043), Finally at BB11..BB11 [043..04F)
  4  ::   5     6  - Try at BB05..BB05 [016..022), Handler at BB07..BB12 [02B..051)
  5  ::   8     6  - Try at BB05..BB05 [016..022), Handler at BB13..BB13 [051..05A)
  6  ::   7        - Try at BB02..BB02 [000..00C), Handler at BB04..BB14 [015..05C)
  7  ::   8        - Try at BB02..BB02 [000..00C), Handler at BB15..BB15 [05C..065)
  8  ::            - Try at BB02..BB15 [000..065), Finally at BB16..BB16 [065..06C)
```
There are two sets of mutually protecting handlers: {`H0`, `H6`, `H7`} and {`H1`, `H4`, `H5`}.

**Comment by SingleAccretion** [comment]
@dotnet/nativeaot-llvm

**Review by yowl — APPROVED** [review]
Thanks, LGTM
