### PR TITLE
Fix behavior of interface dispatch on null instances

### LINKED ISSUE #221: NullReferenceException not thrown for nullref in RhpInterfaceDispatch2
Loader/classloader/methodoverriding/regressions/549411/exploit

We tear down the process instead.

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
An interface call with a null `this` needs to throw a `NullReferenceException`. There are two ways to achieve that: either codegen can insert explicit code to trigger a NullRef at the callsite (before calling into the runtime library to do the dispatch), or the runtime library needs to be able to unwind the helper code that tries to resolve the dispatch and blame the callsite. .NET Native did the former, but the latter produces smaller code (no need to insert the checks). The CoreRT runtime doesn't have code to handle the latter. This pull request is adding that.

The fix is relatively straightforward - we mark locations in the helper where AV can occur. If an AV occurs outside managed code, we check whether it's one of the known locations. If so, we remove the helper method frame off the stack and pretend the AV happened in the calling code.

The one-liner fix in CorInfoImpl fixes an unintialized value problem that basically made us roll a dice on whether to do an explicit nullcheck at the callsite.

Fixes #221.

### CODE REVIEW

File: src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp [hunk 1]
```diff
@@ -390,6 +452,39 @@ Int32 __stdcall RhpHardwareExceptionHandler(UIntNative faultCode, UIntNative fau
...
+        // If this was an AV and code manager is null, this was an AV in unmanaged code.
+        // Could still be an AV in one of our assembly helpers that we know how to handle.
+        bool inWriteBarrierHelper = InWriteBarrierHelper(faultingIP);
+        bool inInterfaceDispatchHelper = InInterfaceDispatchHelper(faultingIP);
+
+        if (inWriteBarrierHelper || inInterfaceDispatchHelper)
+        {
+            if (faultAddress < NULL_AREA_SIZE)
+            {
+                faultCode = STATUS_REDHAWK_WRITE_BARRIER_NULL_REFERENCE;
```
Comment (MichalStrehovsky) [inline src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:468]: I'm considering to renaming this to something else, but don't have a good name.

File: src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp [hunk 2]
```diff
@@ -356,6 +356,73 @@ static UIntNative UnwindWriteBarrierToCaller(
...
+
+        if (interfaceDispatchAVLocations[i] == faultingIP)
+            return true;
+    }
+#endif // USE_PORTABLE_HELPERS
+
+    return false;
+}
+
+static UIntNative UnwindInterfaceDispatchToCaller(
```
Comment (MichalStrehovsky) [inline src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:400]: This is the exact same code as the write barriers unwinder. I could just rename that one to a common name and call it.

I just wasn't sure whether this code could be different for other arches since here we have an unknown number of parameters. It happens to not be a problem on x64. I don't know about x86.

File: src/coreclr/src/nativeaot/Runtime/amd64/StubDispatch.asm [hunk 3]
```diff
@@ -85,6 +91,11 @@ LEAF_END RhpVTableOffsetDispatch, _TEXT
 ;; Initial dispatch on an interface when we don't have a cache yet.
 LEAF_ENTRY RhpInitialInterfaceDispatch, _TEXT
 ALTERNATE_ENTRY RhpInitialDynamicInterfaceDispatch
+        ;; Trigger an AV if we're dispatching on a null this.
+        ;; The exception handling infrastructure is aware of the fact that this is the first
+        ;; instruction of RhpInitialInterfaceDispatch and uses it to translate an AV here
+        ;; to a NullReferenceException at the callsite.
+        cmp     qword ptr [rcx], 0
```
Comment (MichalStrehovsky) [inline src/coreclr/src/nativeaot/Runtime/amd64/StubDispatch.asm:98]: This is technically not necessary since the AV will happen in Runtime.Base, but it's going to throw the Runtime.Base's NullReferenceException that would not be catchable in the original Redhawk model.

File: src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp (hunk 1 above)
Comment (Suchiman) [reply src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:468]: How about one of?
`STATUS_REDHAWK_HELPER_CODE_NULL_REFERENCE`
`STATUS_REDHAWK_NATIVE_HELPER_NULL_REFERENCE`
`STATUS_REDHAWK_UNMANAGED_HELPER_NULL_REFERENCE`
`STATUS_REDHAWK_MANUALLY_MANAGED_NULL_REFERENCE`

File: src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:400]: x86 is full of problems that none of the other platforms have. I think having the unwinder shared would be a good idea.

Comment (jkotas) [reply src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:400]: (If we ever do x86 for completeness, we may want to do it using cdecl callconv to avoid all special casing.)

File: src/coreclr/src/nativeaot/Runtime/amd64/StubDispatch.S [hunk 4]
```diff
@@ -64,6 +69,11 @@ LEAF_END RhpVTableOffsetDispatch, _TEXT
 // Initial dispatch on an interface when we don't have a cache yet.
 LEAF_ENTRY RhpInitialInterfaceDispatch, _TEXT
 ALTERNATE_ENTRY RhpInitialDynamicInterfaceDispatch
+        // Trigger an AV if we're dispatching on a null this.
```
Comment (jkotas) [inline src/coreclr/src/nativeaot/Runtime/amd64/StubDispatch.S:72]: Nit: It may be nice to add these to the ARM64 ones too while you are on it.

File: src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:468]: Or just `STATUS_REDHAWK_NULL_REFERENCE` ?

Comment (MichalStrehovsky) [reply src/coreclr/src/nativeaot/Runtime/EHHelpers.cpp:468]: STATUS_REDHAWK_NULL_REFERENCE is already taken and apparently we need to be able to distinguish between these two cases in the frame iterator.

I like STATUS_REDHAWK_UNMANAGED_HELPER_NULL_REFERENCE. Thanks!

**Review by jkotas — APPROVED** [review]
