### PR TITLE
Fix and simplify UOH object publishing

### LINKED ISSUE #939: Unable to allocate very big arrays
We have System.Runtime tests that test allocating the maximally supported arrays. We throw an OutOfMemoryException for them. Likely because this code:

https://github.com/dotnet/runtimelab/blob/8fac0a891011eda3633270199934019faeea002c/src/coreclr/nativeaot/Runtime/gcrhenv.cpp#L239-L263

Is checking the allocation size instead of element count. Allocation size has already been aligned up.

### LINKED ISSUE #940: Libraries tests are failing when background GC is enabled
I'm either seeing deadlock with this spinning in the retry loop because no other threads are active:

```
>	System.Runtime.Tests.exe!WKS::exclusive_sync::bgc_mark_set(unsigned char * obj) Line 1145	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::revisit_written_page(unsigned char * page, unsigned char * end, int concurrent_p, unsigned char * & last_page, unsigned char * & last_object, int large_objects_p, unsigned __int64 & num_marked_objects) Line 31044	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::revisit_written_pages(int concurrent_p, int reset_only_p) Line 31290	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::background_mark_phase() Line 30597	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::gc1() Line 18891	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::bgc_thread_function() Line 31740	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::bgc_thread_stub(void * arg) Line 29752	C++
 	System.Runtime.Tests.exe!GCToEEInterface::CreateThread::__l2::<lambda>(void * argument) Line 1382	C++
```

Or an INT 3/crash with:

```
>	[Inline Frame] System.Runtime.Tests.exe!WKS::exclusive_sync::check() Line 1124	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::background_mark_phase() Line 30681	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::gc1() Line 18893	C++
 	System.Runtime.Tests.exe!WKS::gc_heap::bgc_thread_function() Line 31740	C++
 	System.Runtime.Tests.exe!GCToEEInterface::CreateThread::__l2::<lambda>(void * argument) Line 1383	C++
```

Both of these are in `exclusive_sync`, so I assume they're related.

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #939
Fixes #940

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/GCHelpers.cpp [hunk 1]
```diff
@@ -329,47 +329,7 @@ EXTERN_C REDHAWK_API int64_t __cdecl RhGetTotalAllocatedBytesPrecise()
...
-        }
-    }
-    else
-#endif // !HOST_64BIT
-    {
-        size = (size_t)pArrayEEType->get_BaseSize() + ((size_t)numElements * (size_t)pArrayEEType->get_ComponentSize());
-        size = ALIGN_UP(size, sizeof(uintptr_t));
-    }
-
-    Array* pArray = (Array*)GcAllocInternal(pArrayEEType, flags, size, pThread);
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/GCHelpers.cpp:359]: This was one of the problems: GcAllocInternal decided to allocate on LOH, but it would not set the flag in this method to call PublishObject below.

File: src/coreclr/nativeaot/Runtime/gcrhenv.cpp [hunk 2]
```diff
@@ -212,74 +212,104 @@ bool RedhawkGCInterface::InitializeSubsystems()
...
 
-void* GcAllocInternal(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, Thread* pThread)
+Object* GcAllocInternal(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, Thread* pThread)
 {
     ASSERT(!pThread->IsDoNotTriggerGcSet());
 
-    if (cbSize >= RH_LARGE_OBJECT_SIZE)
+    size_t cbSize = pEEType->get_BaseSize();
+
+    if (pEEType->get_ComponentSize() != 0)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/gcrhenv.cpp:212]: There are a few extra if-checks and an extra multiplication compared to what it used to be, but it is so much simpler and with less assembly code to have everything centralized in one method.

File: src/coreclr/nativeaot/Runtime/amd64/AllocFast.asm [hunk 3]
```diff
@@ -65,25 +65,15 @@ NESTED_ENTRY RhpNewObject, _TEXT
...
         call        RhpGcAlloc
 
         ;; Set the new object's EEType pointer on success.
         test        rax, rax
         jz          NewOutOfMemory
-        mov         [rax + OFFSETOF__Object__m_pEEType], rsi
-
-        ;; If the object is bigger than RH_LARGE_OBJECT_SIZE, we must publish it to the BGC
-        mov         edx, [rsi + OFFSETOF__EEType__m_uBaseSize]
-        cmp         rdx, RH_LARGE_OBJECT_SIZE
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/amd64/AllocFast.asm:81]: The large object check should be unnecessary in the fast path. There is an assert to protect it in the slow path.

Removing this useless check should make the regular object allocations a tiny bit faster.

File: src/coreclr/nativeaot/Runtime/arm/AllocFast.asm [hunk 4]
```diff
@@ -76,26 +76,14 @@ AllocFailed
...
         mov         r5, r0
 
-        ldr         r2, [r0, #OFFSETOF__EEType__m_uBaseSize]    ; cbSize
+        mov         r2, #0              ; numElements
 
-        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         blx         RhpGcAlloc
 
         ;; Set the new object's EEType pointer on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/arm/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/amd64/AllocFast.asm [hunk 5]
```diff
@@ -226,33 +215,19 @@ NESTED_ENTRY RhpNewArrayRare, _TEXT
...
         xor         rdx, rdx        ; uFlags
-        ; pasing size in r8
         ; pasing pTransitionFrame in r9
 
         ; Call the rest of the allocation helper.
-        ; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        RhpGcAlloc
 
         ; Set the new object's EEType pointer and length on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/amd64/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/amd64/AllocFast.asm [hunk 6]
```diff
@@ -65,25 +65,15 @@ NESTED_ENTRY RhpNewObject, _TEXT
...
 
-        mov         r8d, [rsi + OFFSETOF__EEType__m_uBaseSize]      ; cbSize
+        xor         r8d, r8d        ; numElements
 
         ;; Call the rest of the allocation helper.
-        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        RhpGcAlloc
 
         ;; Set the new object's EEType pointer on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/amd64/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/amd64/AllocFast.S [hunk 7]
```diff
@@ -292,35 +279,20 @@ NESTED_ENTRY RhpNewArrayRare, _TEXT, NoHandler
...
         xor         rsi, rsi        // uFlags
-        // pasing size in rdx
         // pasing pTransitionFrame in rcx
 
         // Call the rest of the allocation helper.
-        // void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        // void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        C_FUNC(RhpGcAlloc)
 
         // Set the new object's EEType pointer and length on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/amd64/AllocFast.S]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/amd64/AllocFast.S [hunk 8]
```diff
@@ -77,27 +77,15 @@ NESTED_ENTRY RhpNewObject, _TEXT, NoHandler
...
 
-        mov         edx, [rdi + OFFSETOF__EEType__m_uBaseSize]      // cbSize
+        xor         edx, edx    // numElements
 
         // Call the rest of the allocation helper.
-        // void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        // void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        C_FUNC(RhpGcAlloc)
 
         // Set the new object's EEType pointer on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/amd64/AllocFast.S]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/arm/AllocFast.S [hunk 9]
```diff
@@ -71,29 +71,13 @@ NESTED_ENTRY RhpNewObject, _TEXT, NoHandler
...
         mov         r5, r0
 
-        ldr         r2, [r0, #OFFSETOF__EEType__m_uBaseSize]    // cbSize
+        mov         r2, #0              // numElements
 
-        // void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        // void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         blx         C_FUNC(RhpGcAlloc)
 
         // Set the new object's EEType pointer on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/arm/AllocFast.S]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/arm64/AllocFast.asm [hunk 10]
```diff
@@ -245,33 +231,16 @@ ArraySizeOverflow
...
 
-        mov         x1, #0
+        mov         x2, x1              ; numElements
+        mov         x1, #0              ; uFlags
 
-        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         bl          RhpGcAlloc
 
         ; Set the new object's EEType pointer and length on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/arm64/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/i386/AllocFast.asm [hunk 11]
```diff
@@ -59,26 +57,16 @@ AllocFailed:
...
-        push        dword ptr [ecx + OFFSETOF__EEType__m_uBaseSize] ; Size
+        push        0                                               ; numElements
         xor         edx, edx                                        ; Flags
         ;; Passing EEType in ecx
 
-        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        RhpGcAlloc
 
         ;; Set the new object's EEType pointer on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/i386/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/i386/AllocFast.asm [hunk 12]
```diff
@@ -116,26 +104,16 @@ FASTCALL_FUNC   RhpNewFinalizable, 4
...
-        push        dword ptr [ecx + OFFSETOF__EEType__m_uBaseSize] ; Size
+        push        0                                               ; numElements
         mov         edx, GC_ALLOC_FINALIZE                          ; Flags
         ;; Passing EEType in ecx
 
-        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        RhpGcAlloc
 
         ;; Set the new object's EEType pointer on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/i386/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/i386/AllocFast.asm [hunk 13]
```diff
@@ -224,38 +202,22 @@ StringAllocContextOverflow:
...
-        push        edi                                             ; Size
+        push        [ebp - 4]                                       ; numElements
         xor         edx, edx                                        ; Flags
         ;; Passing EEType in ecx
 
-        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t cbSize, void * pTransitionFrame)
+        ;; void* RhpGcAlloc(EEType *pEEType, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame)
         call        RhpGcAlloc
 
         ; Set the new object's EEType pointer and length on success.
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/i386/AllocFast.asm]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/i386/AllocFast.asm [hunk 14]
```diff
@@ -371,38 +333,22 @@ ArrayAllocContextOverflow:
...
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/i386/AllocFast.asm]:
```suggestion
```

**Review by MichalStrehovsky — APPROVED** [review]
So much simpler! Thank you!
