### PR TITLE
Fix conditions for implicit use of hardware intrinsics

### LINKED ISSUE #425: [NativeAOT] Illegal instruction (core dumped) - Ubuntu 20.04
A linux user reported me this issue when using my application launcher built with .NET 5 and latest NativeAOT.
Other linux users everything works fine.
image

You can find the application here: https://www.classicuo.eu/launcher/linux-x64/ClassicUOLauncher-linux-x64-release.zip

This is the cpuinfo:
```
rocessor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 2
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 3
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
```

```
X@X-workstation:~/Desktop/CUOLAUNCHER$ gdb ./ClassicUOLauncher 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./ClassicUOLauncher...
ru(gdb) run
Starting program: /home/jhendric/Desktop/CUOLAUNCHER/ClassicUOLauncher 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd7370700 (LWP 50780)]

Thread 1 "ClassicUOLaunch" received signal SIGILL, Illegal instruction.
0x0000000000853af9 in S_P_CoreLib_System_SpanHelpers__IndexOf_0 (searchSpace=@0x7fffffffe2bf: 47 '/', value=0 '\000', length=2147483647)
    at /_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs:348
348	/_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs: No such file or directory.
(gdb) bt
#0  0x0000000000853af9 in S_P_CoreLib_System_SpanHelpers__IndexOf_0 (searchSpace=@0x7fffffffe2bf: 47 '/', value=0 '\000', length=2147483647)
    at /_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs:348
#1  0x000000000081184d in String__Ctor_3 (value=0x7fffffffe2bf "/home/jhendric/Desktop/CUOLAUNCHER/ClassicUOLauncher") at /_/src/libraries/System.Private.CoreLib/src/System/String.cs:189
#2  0x00000000008fdafe in S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeCommandLineArgs (argc=1, argv=0x7fffffffdf98)
    at /_/src/coreclr/src/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerHelpers/StartupCode/StartupCodeHelpers.Extensions.cs:31
#3  0x0000000000c6cde1 in ClassicUOLauncher__Module___StartupCodeMain () at <stdin>:15732480
#4  0x000000000041b2e9 in main (argc=1, argv=0x7fffffffdf98) at /__w/1/s/src/coreclr/src/nativeaot/Bootstrap/main.cpp:186
(gdb) quit
A debugging session is active.

	Inferior 1 [process 50776] will be killed.

Quit anyway? (y or n) y
```

### PR DESCRIPTION
**Pull request by jkotas**
JIT uses hardware intrinsics implicitly in certain cases. Unlike regular hardware intrinsics, these
transformations are not guarded using explicit IsSupported checks. NativeAOT had fragile code that tried
to step around this limitation. This change makes this contract explicit by allowing notifyInstructionSetUsage
callback to return bool that the EE side can use to suppress implicit use of hardware intrinsics.

Fixes #425

### CODE REVIEW

File: src/coreclr/src/tools/aot/ILCompiler/Program.cs [hunk 1]
```diff
@@ -369,14 +369,13 @@ private int Run(string[] args)
...
                 optimisticInstructionSetSupportBuilder.AddSupportedInstructionSet("aes");
                 optimisticInstructionSetSupportBuilder.AddSupportedInstructionSet("pclmul");
                 optimisticInstructionSetSupportBuilder.AddSupportedInstructionSet("lzcnt");
 
-                // NOTE: we don't optimistically enable SSE4.1/SSE4.2 because RyuJIT can opportunistically use
-                // these instructions in e.g. optimizing Math.Round or Vector<T> operations without IsSupported guards.
-
                 // If SSE4.2 was enabled, we can also opportunistically enable POPCNT
                 Debug.Assert(InstructionSet.X64_SSE42 == InstructionSet.X86_SSE42);
                 if (supportedInstructionSet.HasInstructionSet(InstructionSet.X64_SSE42))
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/aot/ILCompiler/Program.cs:381]: We can take the POPCNT out of this `if` block now since it will always be true.

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

Would it make sense to do this in the runtime repo and ask for David's opinion too? I found this logic (and the previous incarnation of it) always difficult to wrap my head around.

**Comment by MichalStrehovsky** [comment]
> Would it make sense to do this in the runtime repo and ask for David's opinion too? I found this logic (and the previous incarnation of it) always difficult to wrap my head around.

Just saw the other pull request. That's what I get for reading emails oldest to newest and processing them as I go.
